/* SPDX-License-Identifier: BSD-3-Clause */

#ifndef __UK_PLAT_PAL_EXCEPT_H__
#error "Do not include this header directly"
#endif

/*
 * Dummy values for the except IDs, i.e., they are meaningless to a PD,
 * However, they are helpful for supporting compiling the lcpu
 */
#define UK_PAL_ARM64_EXCEPT_EVENT_DEBUG			    0
#define UK_PAL_ARM64_EXCEPT_EVENT_ERR_INVALID_OP	1
#define UK_PAL_ARM64_EXCEPT_EVENT_ERR_PAGE_FAULT	2
#define UK_PAL_ARM64_EXCEPT_EVENT_ERR_BUS_ERROR	    3
#define UK_PAL_ARM64_EXCEPT_EVENT_ERR_MATH		    4
#define UK_PAL_ARM64_EXCEPT_EVENT_ERR_SECURITY	    5
#define UK_PAL_ARM64_EXCEPT_EVENT_SYSCALL			6
#define UK_PAL_ARM64_EXCEPT_EVENT_IRQ				7
#define UK_PAL_ARM64_EXCEPT_EVENT_UNHANDLED		    8

#define UK_PAL_ARCH_EXCEPT_EVENT_DEBUG	\
    UK_PAL_ARM64_EXCEPT_EVENT_DEBUG
#define UK_PAL_ARCH_EXCEPT_EVENT_ERR_INVALID_OP	\
    UK_PAL_ARM64_EXCEPT_EVENT_ERR_INVALID_OP
#define UK_PAL_ARCH_EXCEPT_EVENT_ERR_PAGE_FAULT	\
    UK_PAL_ARM64_EXCEPT_EVENT_ERR_PAGE_FAULT
#define UK_PAL_ARCH_EXCEPT_EVENT_ERR_BUS_ERROR \
    UK_PAL_ARM64_EXCEPT_EVENT_ERR_BUS_ERROR
#define UK_PAL_ARCH_EXCEPT_EVENT_ERR_MATH \
    UK_PAL_ARM64_EXCEPT_EVENT_ERR_MATH
#define UK_PAL_ARCH_EXCEPT_EVENT_ERR_SECURITY \
    UK_PAL_ARM64_EXCEPT_EVENT_ERR_SECURITY
#define UK_PAL_ARCH_EXCEPT_EVENT_SYSCALL \
    UK_PAL_ARM64_EXCEPT_EVENT_SYSCALL
#define UK_PAL_ARCH_EXCEPT_EVENT_IRQ \
    UK_PAL_ARM64_EXCEPT_EVENT_IRQ
#define UK_PAL_ARCH_EXCEPT_EVENT_UNHANDLED \
    UK_PAL_ARM64_EXCEPT_EVENT_UNHANDLED


#define UK_PAL_ARM64_EXCEPT_ID_INVALID_OP \
	UK_PAL_ARM64_EXCEPT_EVENT_ERR_INVALID_OP
#define UK_PAL_ARM64_EXCEPT_ID_DEBUG \
	UK_PAL_ARM64_EXCEPT_EVENT_DEBUG
#define UK_PAL_ARM64_EXCEPT_ID_PAGE_FAULT \
	UK_PAL_ARM64_EXCEPT_EVENT_ERR_PAGE_FAULT
#define UK_PAL_ARM64_EXCEPT_ID_BUS_ERROR \
	UK_PAL_ARM64_EXCEPT_EVENT_ERR_BUS_ERROR
#define UK_PAL_ARM64_EXCEPT_ID_MATH \
	UK_PAL_ARM64_EXCEPT_EVENT_ERR_MATH
#define UK_PAL_ARM64_EXCEPT_ID_SECURITY \
	UK_PAL_ARM64_EXCEPT_EVENT_ERR_SECURITY
#define UK_PAL_ARM64_EXCEPT_ID_SYSCALL \
	UK_PAL_ARM64_EXCEPT_EVENT_SYSCALL
